@Test
public void run() throws Exception {
    File watchDir = new File("target/fake-watch-dir");
    watchDir.mkdirs();
    File assetsDir = new File(watchDir, "assets");
    assetsDir.mkdirs();
    // make sure file does not yet exist
    File newTxtFile = new File(watchDir, "test.txt");
    newTxtFile.delete();
    // file that would be excluded in assets directory, but we'll include a rule to include it
    File newIncludedTxtFile = new File(assetsDir, "included.txt");
    newIncludedTxtFile.delete();
    // make sure file does not yet exist
    File newPngFile = new File(assetsDir, "test.png");
    newPngFile.delete();
    DelayedRestartTrigger restartTrigger = mock(DelayedRestartTrigger.class);
    final WatchAndRestartMachine watcher = new WatchAndRestartMachine(watchDir.toPath(), new HashSet<>(Arrays.asList("(.*)included.txt")), new HashSet<>(Arrays.asList(DEFAULT_EXCLUDE_PATTERNS)), restartTrigger);
    Thread watcherThread = new Thread(watcher);
    watcherThread.start();
    try {
        // add a new file
        OutputStream os = new FileOutputStream(newTxtFile);
        os.close();
        // trigger should have been called soon
        verify(restartTrigger, timeout(10000)).trigger();
        Mockito.reset(restartTrigger);
        // modify the file
        os = new FileOutputStream(newTxtFile);
        os.write("Hello!".getBytes());
        os.close();
        // windows may mod a file more than once
        verify(restartTrigger, timeout(10000).atLeast(1)).trigger();
        verify(restartTrigger, atMost(2)).trigger();
        Mockito.reset(restartTrigger);
        // use an excluded file and verify restart not called
        // add a new file
        os = new FileOutputStream(newPngFile);
        os.close();
        // indicates exclusion rule for new files didn't work
        verify(restartTrigger, Mockito.after(10000).never()).trigger();
        // modify the file
        os = new FileOutputStream(newPngFile);
        os.write("Hello!".getBytes());
        os.close();
        // indicates exclusion rule for modified files didn't work
        verify(restartTrigger, Mockito.after(10000).never()).trigger();
        // add a new file
        os = new FileOutputStream(newIncludedTxtFile);
        os.close();
        // indicates exclusion rule for new files didn't work
        // windows may do 2 mods so we need to check range
        verify(restartTrigger, timeout(10000).atLeast(1)).trigger();
        verify(restartTrigger, atMost(2)).trigger();
    } finally {
        watcher.shutdown();
        watcherThread.interrupt();
    }
}
