#!/bin/bash

virtualenv --python python3 .venv
source .venv/bin/activate
pip3 install -r requirements.txt
# (cd utils;
#  git clone https://github.com/c2nes/javalang.git
#  (cd javalang;
#   python setup.py install
#  )
# )
