#!/bin/bash

function genReport() {
    for x in `find . -name "surefire-reports"`
    do
        for y in `ls $x/*.xml`
        do
            python parse.py $y
        done
    done
}

mvn dependency:go-offline

for x in {1..10}
do
    mvn clean
    mvn test
    genReport &> run${x}.log
done

