#!/bin/bash

(
    for x in `ls *.log`;
    do
        NUM=$(cat $x | wc -l )
        echo $NUM
        # if [ ! $NUM -eq "1290" ]; then
        #     echo $NUM $x
        # fi
    done
) | sort -V | uniq
