@Test
void run() {
    this.context = SpringApplication.run(ExampleWebConfig.class);
    assertThat(this.context).isNotNull();
}
@Override
public void run() {
    SpringApplication application = new SpringApplication(FailingConfig.class);
    application.setWebApplicationType(WebApplicationType.NONE);
    application.run();
}
@Override
public void run(String... args) {
    markAsRan();
}
@Override
public void run(ApplicationArguments args) {
    markAsRan();
}
