#!/bin/bash

function genReport() {
    for x in `find . -name "surefire-reports"`
    do
        for y in `ls $x/*.xml`
        do
            python parse.py $y
        done
    done
}

mvn dependency:go-offline -Dlicense.skip=true

for x in {12..12}
do
    mvn clean 
    mvn test -Dlicense.skip=true
    genReport &> run${x}.log
done

