test.txt
watchDir
newTxtFile
 add a new file
 windows may mod a file more than once
watcherThread
run
(.*)included.txt
DEFAULT_EXCLUDE_PATTERNS
delete
newIncludedTxtFile
asList
timeout
getBytes
included.txt
 modify the file
assets
 indicates exclusion rule for modified files didn't work
interrupt
test.png
verify
 trigger should have been called soon
atMost
after
close
write
watcher
 indicates exclusion rule for new files didn't work
 windows may do 2 mods so we need to check range
 file that would be excluded in assets directory, but we'll include a rule to include it
os
target/fake-watch-dir
start
newPngFile
trigger
restartTrigger
Hello!
never
toPath
Mockito
mkdirs
assetsDir
mock
reset
atLeast
Arrays
shutdown
 make sure file does not yet exist
